#!/bin/bash

cd $HOME

# Check for Command Line Tools
if ! xcode-select -p &> /dev/null; then
    echo "Command Line Tools not found. Installing..."
    xcode-select --install
    read -p "Press enter when the installation is complete"
fi

# Check for Rosetta on Apple Silicon Macs
if [[ $(uname -m) == 'arm64' ]]; then
    if ! /usr/bin/pgrep oahd >/dev/null 2>&1; then
        echo "Rosetta is not installed. Installing..."
        softwareupdate --install-rosetta --agree-to-license
    fi
fi

if ! command -v nix &> /dev/null
then
    echo "Nix not found. Installing Nix..."
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
fi

. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

echo "Applying Nix configuration..."
nix run nix-darwin --experimental-features 'nix-command flakes' -- switch --flake ~/.config/nix-darwin

read -p "Do you want to use Keybase for PGP key management? (y/n) " use_keybase

if [ "$use_keybase" = "y" ]; then
    if ! keybase whoami &> /dev/null; then
        echo "Not logged in to Keybase. Please log in."
        keybase login
    fi

    keybase pgp pull-private --all
fi
