#!/bin/bash

cd $HOME

# Check for Command Line Tools
if ! xcode-select -p &>/dev/null; then
  echo "Command Line Tools not found. Installing..."
  xcode-select --install
  read -p "Press enter when the installation is complete"
fi

# Check for Rosetta on Apple Silicon Macs
if [[ $(uname -m) == 'arm64' ]]; then
  if ! /usr/bin/pgrep oahd >/dev/null 2>&1; then
    echo "Rosetta is not installed. Installing..."
    softwareupdate --install-rosetta --agree-to-license
  fi
fi

# Nix installation and configuration
if ! command -v nix &>/dev/null; then
  echo "Nix not found. Installing Nix..."
  curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
fi

. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

FLAKE=${FLAKE:="$HOME/.config/nix-darwin"}

echo "Applying Nix configuration from $FLAKE..."
nix run nix-darwin --experimental-features 'nix-command flakes' -- switch --flake $FLAKE || exit 1
